/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ggalmazor;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.hasItems;

class Picky {
    @Test
    void test() {
        var pattern = Pattern.compile(" ?([A-Z]{2,4}) ?");
        List<String> tokens = pattern.matcher("foo API bar HTTP baz ").results().map(result -> result.group(1)).collect(Collectors.toList());
        assertThat(tokens, hasItems("API", "HTTP"));
    }
}
