services:
  db:
    image: postgres:16-bookworm
    container_name: picky-dev-database
    ports:
      - 127.0.0.1:5435:5432
    volumes:
      - picky-dev-database-data:/var/lib/postgresql/data
    env_file: .env.db
    networks:
      - picky
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER}
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  picky-dev-database-data:

networks:
  picky:
    name: picky-dev-network
